ALTER SEQUENCE banner_position_id_seq RESTART WITH 10000;
ALTER SEQUENCE banners_id_seq RESTART WITH 10000;
ALTER SEQUENCE comment_info_id_seq RESTART WITH 10000;
ALTER SEQUENCE extend_detail_id_seq RESTART WITH 10000;
ALTER SEQUENCE extend_info_id_seq RESTART WITH 10000;
ALTER SEQUENCE images_id_seq RESTART WITH 10000;
ALTER SEQUENCE kyara_attr_id_seq RESTART WITH 10000;
ALTER SEQUENCE top_banner_attributes_id_seq RESTART WITH 10000;
ALTER SEQUENCE top_banner_display_inventory_id_seq RESTART WITH 10000;
ALTER SEQUENCE top_banners_id_seq RESTART WITH 10000;
ALTER SEQUENCE users_id_seq RESTART WITH 10000;

